In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline


In [2]:
#Verify path to data
import os
print(os.listdir('./input'))


['sample_submission.csv', 'test.tsv', 'train.tsv', 'zipped']


In [3]:
# load training data to dataframe
train_df = pd.read_table("./input/train.tsv")

In [4]:
#review training data
train_df.head()

train_id                                 name  item_condition_id  \
0         0  MLB Cincinnati Reds T Shirt Size XL                  3   
1         1     Razer BlackWidow Chroma Keyboard                  3   
2         2                       AVA-VIV Blouse                  1   
3         3                Leather Horse Statues                  1   
4         4                 24K GOLD plated rose                  1   

                                       category_name brand_name  price  \
0                                  Men/Tops/T-shirts        NaN   10.0   
1  Electronics/Computers & Tablets/Components & P...      Razer   52.0   
2                        Women/Tops & Blouses/Blouse     Target   10.0   
3                 Home/Home Décor/Home Décor Accents        NaN   35.0   
4                            Women/Jewelry/Necklaces        NaN   44.0   

   shipping                                   item_description  
0         1                                 No description yet  
1         0  This keyboard is in great condition and works ...  
2         1  Adorable top with a hint of lace and a key hol...  
3         1  New with tags. Leather horses. Retail for [rm]...  
4         0          Complete with certificate of authenticity

Condition ID's
1 - New
2 - Like New
3 - Good
4 - Fair
5 - Poor

Clothing
1 - New: NWT (New With Tags), unworn, unaltered and includes the original tags.
2 - Like New: NWOT (New without tags) or very lightly used with no flaws or damage.
3 - Good: Gently used but still may have minor flaws such as pilling, stretching, or loose threads.
4 - Fair: Multiple minor flaws, defects, or damage such as rips, light stains, pilling.
5 - Poor: Heavily used and has major cosmetic flaws or damage such as holes, stains, fading, or missing buttons/beads.

Shoes 
1 - New: New, unworn and still in the original box.
2 - Like New: Unworn or only tried on. No creases, but may not be in the original box.
3 - Good: Used, but there are only a few minor flaws such as slight wear on the sole, light creases, or small scuffs.
4 - Fair: Show signs of wear and has multiple major flaws, such as holes, rips, creases, or stains, but the sole is intact.
5 - Poor: Heavily worn and have multiple major flaws, such as large holes, stains, scuffs, or the soles are not intact.

Electronics
1 - New: Unused in the original packaging.
2 - Like New: lightly used and fully functional, but does not include the original packaging.
3 - Good: Gently used and may have minor cosmetic flaws, but is fully functional.
4 - Fair: Used and has multiple flaws but is overall functional.
5 - Poor: Heavily used, has major cosmetic flaws or damage, non-functional or sold as parts.

Condition comments may appear in name or description
1 - New
    BNWT: Brand New With Tags
    BNIP: Brand New In Packet 
    MIB: Mint In Box
    NWT: New With Tags
    NIB: New In Box
    BNIB: Brand New In Box

2 - Like New
    BNWOT: Brand New Without Tags
    MWOB: Mint With Out Box
    NWOT: New without tags or very lightly used with no flaws or damage
    BNWOB: Brand New Without Box


In [5]:
# Summary stats for numeric fields. Not much useful here other than price.
train_df.describe()

train_id  item_condition_id         price      shipping
count  1.482535e+06       1.482535e+06  1.482535e+06  1.482535e+06
mean   7.412670e+05       1.907380e+00  2.673752e+01  4.472744e-01
std    4.279711e+05       9.031586e-01  3.858607e+01  4.972124e-01
min    0.000000e+00       1.000000e+00  0.000000e+00  0.000000e+00
25%    3.706335e+05       1.000000e+00  1.000000e+01  0.000000e+00
50%    7.412670e+05       2.000000e+00  1.700000e+01  0.000000e+00
75%    1.111900e+06       3.000000e+00  2.900000e+01  1.000000e+00
max    1.482534e+06       5.000000e+00  2.009000e+03  1.000000e+00

In [6]:
#Describe the values of the category name feature
train_df['category_name'].describe()

count                                            1476208
unique                                              1287
top       Women/Athletic Apparel/Pants, Tights, Leggings
freq                                               60177
Name: category_name, dtype: object

In [7]:
#Grouping by category name, get summary stats for price and load the results into their own dataframe.
category_price_df = train_df.groupby('category_name').describe()['price'].reset_index()
print(category_price_df)

                                     category_name    count        mean  \
0                          Beauty/Bath & Body/Bath   5049.0   18.481878   
1           Beauty/Bath & Body/Bathing Accessories    332.0   21.882530   
2                     Beauty/Bath & Body/Cleansers    723.0   13.564315   
3                         Beauty/Bath & Body/Other    147.0   20.469388   
4      Beauty/Bath & Body/Scrubs & Body Treatments    812.0   24.640394   
5                          Beauty/Bath & Body/Sets    695.0   21.086331   
6           Beauty/Fragrance/Candles & Home Scents   2965.0   21.093423   
7                            Beauty/Fragrance/Kids     87.0    8.379310   
8                             Beauty/Fragrance/Men   2114.0   28.555818   
9                           Beauty/Fragrance/Other     39.0   24.794872   
10                           Beauty/Fragrance/Sets    461.0   25.603037   
11                          Beauty/Fragrance/Women  18628.0   23.717790   
12                   Beau

In [8]:
# Show price stats for Men/Tops/T-shirts
category_price_df.loc[category_price_df['category_name'] == 'Men/Tops/T-shirts']

category_name    count       mean        std  min   25%   50%   75%  \
808  Men/Tops/T-shirts  15108.0  18.352495  16.307762  0.0  10.0  14.0  20.0   

       max  
808  309.0

In [9]:
# Feature extraction from text
# Method: bag of words 
# https://pythonprogramminglanguage.com
 
from sklearn.feature_extraction.text import CountVectorizer

# create a dataframe for rows with category of "Men/Tops/T-shirts"
MensTees_df = train_df.loc[train_df['category_name'] == 'Men/Tops/T-shirts']

# Summary stats. Verify they match cell above.
MensTees_df.describe() 

train_id  item_condition_id         price      shipping
count  1.510800e+04       15108.000000  15108.000000  15108.000000
mean   7.374128e+05           2.142441     18.352495      0.394559
std    4.273357e+05           0.871937     16.307762      0.488772
min    0.000000e+00           1.000000      0.000000      0.000000
25%    3.732120e+05           1.000000     10.000000      0.000000
50%    7.299650e+05           2.000000     14.000000      0.000000
75%    1.113179e+06           3.000000     20.000000      1.000000
max    1.482464e+06           5.000000    309.000000      1.000000

In [10]:
#Create a corpus of words in the item description for this category
corpus = MensTees_df['item_description'][pd.notnull(MensTees_df['item_description'])]

In [11]:
#Describe the values in the corpus
corpus.describe()

count                  15108
unique                 12860
top       No description yet
freq                    1257
Name: item_description, dtype: object

In [12]:
vectorizer = CountVectorizer(stop_words="english")

In [13]:
#print sparse array
print(vectorizer.fit_transform(corpus).toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
#Print length of vocabulary and dictionary entries. For 15K rows, there are almost 9400 distinct words.
print(len(vectorizer.vocabulary_)), print( vectorizer.vocabulary_ )

9393
{'description': 2482, 'worn': 9205, 'washed': 9017, 'sent': 7290, 'men': 5264, 'nike': 5696, 'dri': 2731, 'fit': 3234, 'shirt': 7391, 'blue': 1220, 'items': 4335, 'come': 1999, 'clean': 1871, 'smoke': 7597, 'pet': 6147, 'free': 3379, 'home': 4016, 'brand': 1349, 'new': 5662, 'tags': 8147, 'white': 9096, 'burgundy': 1491, 'mens': 5270, 'xxl': 9286, 'cruise': 2260, 'ship': 7381, 'shirts': 7395, 'grey': 3694, 'royal': 7038, 'caribbean': 1630, 'pocket': 6287, 'embroidered': 2896, 'blank': 1184, 'soverign': 7698, 'seas': 7244, 'graphic': 3660, 'nwot': 5775, 'black': 1174, 'tee': 8229, 'screen': 7213, 'print': 6427, 'garbage': 3481, 'lettering': 4794, 'size': 7493, 'good': 3614, 'condition': 2058, 'official': 5822, 'licensed': 4810, 'product': 6449, '2xl': 212, 'like': 4827, 'quality': 6567, 'material': 5180, 'staple': 7834, 'piece': 6189, 'basically': 991, 'wear': 9046, 'tear': 8215, 'great': 3674, 'soft': 7642, 'used': 8782, 'barely': 968, 'tell': 8244, 'cleaning': 1874, 'closet': 190

(None, None)

In [15]:
#Print vectorizer stop words
vectorizer.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [16]:
#Transform to a sorted list to illustrate the frequency of words in the corpus
transformed = vectorizer.fit_transform(corpus)
sparse_sums = transformed.sum(axis = 0)
feature_names = vectorizer.get_feature_names()
sorted_word_counts = sorted(zip(feature_names, sparse_sums.tolist()[0]), key = lambda x: x[1], reverse = True)
print(sorted_word_counts)

[('size', 6647), ('shirt', 6174), ('new', 3929), ('condition', 3526), ('men', 3085), ('worn', 2640), ('large', 2562), ('medium', 2243), ('brand', 2226), ('small', 1853), ('xl', 1831), ('free', 1827), ('black', 1578), ('shipping', 1516), ('tee', 1509), ('great', 1508), ('tags', 1505), ('good', 1493), ('description', 1311), ('rm', 1295), ('like', 1287), ('shirts', 1178), ('sleeve', 1135), ('color', 1008), ('blue', 989), ('white', 953), ('bundle', 907), ('price', 880), ('cotton', 851), ('stains', 847), ('nike', 828), ('long', 822), ('100', 772), ('fit', 738), ('items', 719), ('tshirt', 694), ('mens', 677), ('used', 627), ('vintage', 609), ('home', 606), ('fits', 597), ('smoke', 591), ('tag', 584), ('logo', 546), ('polo', 537), ('red', 515), ('ship', 508), ('firm', 499), ('authentic', 495), ('times', 491), ('ask', 479), ('just', 476), ('excellent', 469), ('wear', 468), ('check', 454), ('short', 439), ('flaws', 432), ('neck', 426), ('gray', 423), ('xxl', 423), ('navy', 416), ('holes', 415),

In [30]:
top_n_words = [i[0] for i in sorted_word_counts[:100]]
print(len(top_n_words)), top_n_words

100


(None,
 ['size',
  'shirt',
  'new',
  'condition',
  'men',
  'worn',
  'large',
  'medium',
  'brand',
  'small',
  'xl',
  'free',
  'black',
  'shipping',
  'tee',
  'great',
  'tags',
  'good',
  'description',
  'rm',
  'like',
  'shirts',
  'sleeve',
  'color',
  'blue',
  'white',
  'bundle',
  'price',
  'cotton',
  'stains',
  'nike',
  'long',
  '100',
  'fit',
  'items',
  'tshirt',
  'mens',
  'used',
  'vintage',
  'home',
  'fits',
  'smoke',
  'tag',
  'logo',
  'polo',
  'red',
  'ship',
  'firm',
  'authentic',
  'times',
  'ask',
  'just',
  'excellent',
  'wear',
  'check',
  'short',
  'flaws',
  'neck',
  'gray',
  'xxl',
  'navy',
  'holes',
  'sizes',
  'grey',
  'american',
  '2xl',
  'rips',
  'unisex',
  'adidas',
  'questions',
  'supreme',
  'perfect',
  'green',
  'day',
  'soft',
  'band',
  'graphic',
  'save',
  'item',
  '10',
  'super',
  'jordan',
  'washed',
  'bought',
  'available',
  'bape',
  'sleeves',
  'nwt',
  'offers',
  'comes',
  'light',

In [17]:
# Find words that appear more than the specified number of times
# Set to 250 to get a list of 100 words for thsi example
def filter_value( wordList, frequency ):
    for x, y in wordList:
        if y > frequency :
            yield x

frequent_words= list( filter_value( sorted_word_counts, 250 ) )
print(len(frequent_words)), print(frequent_words)


100
['size', 'shirt', 'new', 'condition', 'men', 'worn', 'large', 'medium', 'brand', 'small', 'xl', 'free', 'black', 'shipping', 'tee', 'great', 'tags', 'good', 'description', 'rm', 'like', 'shirts', 'sleeve', 'color', 'blue', 'white', 'bundle', 'price', 'cotton', 'stains', 'nike', 'long', '100', 'fit', 'items', 'tshirt', 'mens', 'used', 'vintage', 'home', 'fits', 'smoke', 'tag', 'logo', 'polo', 'red', 'ship', 'firm', 'authentic', 'times', 'ask', 'just', 'excellent', 'wear', 'check', 'short', 'flaws', 'neck', 'gray', 'xxl', 'navy', 'holes', 'sizes', 'grey', 'american', '2xl', 'rips', 'unisex', 'adidas', 'questions', 'supreme', 'perfect', 'green', 'day', 'soft', 'band', 'graphic', 'save', 'item', '10', 'super', 'jordan', 'washed', 'bought', 'available', 'bape', 'sleeves', 'nwt', 'offers', 'comes', 'light', 'listings', 'nice', 'extra', 'tears', 'ralph', 'lauren', 'pink', 'women', 'don']


(None, None)

In [39]:
mens_Ts_cat_desc_price_df = category_price_df.loc[category_price_df['category_name'] == 'Men/Tops/T-shirts'].reset_index()
mens_Ts_cat_desc_price_df

index      category_name    count       mean        std  min   25%   50%  \
0    808  Men/Tops/T-shirts  15108.0  18.352495  16.307762  0.0  10.0  14.0   

    75%    max  
0  20.0  309.0

In [40]:
mens_Ts_cat_desc_price_df = category_price_df.loc[category_price_df['category_name'] == 'Men/Tops/T-shirts'].reset_index()
mens_Ts_cat_desc_price_df = mens_Ts_cat_desc_price_df.drop(['index'], axis=1)
mens_Ts_cat_desc_price_df

category_name    count       mean        std  min   25%   50%   75%  \
0  Men/Tops/T-shirts  15108.0  18.352495  16.307762  0.0  10.0  14.0  20.0   

     max  
0  309.0

In [41]:
mens_Ts_cat_desc_price_df['desc_word'] = pd.Series(['all'])
mens_Ts_cat_desc_price_df

category_name    count       mean        std  min   25%   50%   75%  \
0  Men/Tops/T-shirts  15108.0  18.352495  16.307762  0.0  10.0  14.0  20.0   

     max desc_word  
0  309.0       all

In [20]:
MensTees_df[MensTees_df['item_description'].str.contains('size')].describe()['price']

count    3164.000000
mean       18.541719
std        15.119332
min         0.000000
25%        10.000000
50%        14.000000
75%        20.000000
max       215.000000
Name: price, dtype: float64

In [42]:
mens_Ts_cat_desc_price_df.loc[mens_Ts_cat_desc_price_df.index.max() + 1] = MensTees_df[MensTees_df['item_description'].str.contains('size')].describe()['price']
mens_Ts_cat_desc_price_df.loc[mens_Ts_cat_desc_price_df.index.max(), 'category_name'] = 'Men/Tops/T-shirts'
mens_Ts_cat_desc_price_df.loc[mens_Ts_cat_desc_price_df.index.max(), 'desc_word'] = 'size'
mens_Ts_cat_desc_price_df

category_name    count       mean        std  min   25%   50%   75%  \
0  Men/Tops/T-shirts  15108.0  18.352495  16.307762  0.0  10.0  14.0  20.0   
1  Men/Tops/T-shirts   3164.0  18.541719  15.119332  0.0  10.0  14.0  20.0   

     max desc_word  
0  309.0       all  
1  215.0      size

In [80]:
##############################
##############################
##############################
import sys
import time

category_name = 'Men/Tops/T-shirts'
num_words = 100

cat_desc_price_df = pd.DataFrame(columns=["category_name", "count", "mean", "std", "min", "25%", "50%", "75%", "max", "desc"])
cat_row = category_price_df.loc[category_price_df['category_name'] == 'Men/Tops/T-shirts']
cat_desc_price_df = cat_desc_price_df.append({
        "category_name": category_name, 
        "count": cat_row.get(0), 
        "mean": cat_row.get(1), 
        "std": cat_row.get(2), 
        "min": cat_row.get(3), 
        "25%": cat_row.get(4), 
        "50%": cat_row.get(5), 
        "75%": cat_row.get(6), 
        "max": cat_row.get(7), 
        "desc_word": "all"
    }, ignore_index=True)

corpus = train_df.loc[train_df['category_name'] == category_name]['item_description'][pd.notnull(train_df['item_description'])]

#Transform to a sorted list to illustrate the frequency of words in the corpus
transformed = vectorizer.fit_transform(corpus)
sparse_sums = transformed.sum(axis = 0)
feature_names = vectorizer.get_feature_names()
sorted_word_counts = sorted(zip(feature_names, sparse_sums.tolist()[0]), key = lambda x: x[1], reverse = True)

# Find top n words in sorted list
top_n_words = [i[0] for i in sorted_word_counts[:num_words]]

for word in top_n_words:
    row = train_df.loc[(train_df['category_name'] == category_name) & (train_df['item_description'].str.contains(word))].describe()['price']    
    cat_desc_price_df = cat_desc_price_df.append({
        "category_name": category_name, 
        "count": row.get(0), 
        "mean": row.get(1), 
        "std": row.get(2), 
        "min": row.get(3), 
        "25%": row.get(4), 
        "50%": row.get(5), 
        "75%": row.get(6), 
        "max": row.get(7), 
        "desc_word": word
    }, ignore_index=True)

cat_desc_price_df


category_name   count       mean        std  min    25%   50%    75%  \
0    Men/Tops/T-shirts     NaN        NaN        NaN  NaN    NaN   NaN    NaN   
1    Men/Tops/T-shirts  3164.0  18.541719  15.119332  0.0  10.00  14.0  20.00   
2    Men/Tops/T-shirts  4999.0  17.402180  14.007666  0.0  10.00  14.0  20.00   
3    Men/Tops/T-shirts  2314.0  21.748487  18.280724  0.0  11.00  16.0  25.00   
4    Men/Tops/T-shirts  3076.0  15.951073  11.948901  0.0  10.00  13.0  18.00   
5    Men/Tops/T-shirts  1990.0  18.253266  14.863893  0.0  10.00  14.0  21.00   
6    Men/Tops/T-shirts  1999.0  17.870435  14.748805  0.0  10.00  14.0  20.00   
7    Men/Tops/T-shirts  1497.0  17.609552  14.727925  0.0  10.00  14.0  20.00   
8    Men/Tops/T-shirts  1380.0  19.302174  18.128119  0.0  10.00  14.0  20.25   
9    Men/Tops/T-shirts   780.0  19.247436  15.765012  0.0  11.00  15.0  20.00   
10   Men/Tops/T-shirts  1258.0  19.756757  16.500562  3.0  10.00  15.0  23.00   
11   Men/Tops/T-shirts   389.0  19.591260  19.342012  3.0  10.00  14.0  22.00   
12   Men/Tops/T-shirts   981.0  15.798165  10.746335  0.0  10.00  13.0  19.00   
13   Men/Tops/T-shirts   716.0  17.592179  15.425658  0.0  10.00  14.0  19.00   
14   Men/Tops/T-shirts   843.0  16.794187  12.747201  0.0  10.00  14.0  20.00   
15   Men/Tops/T-shirts  1157.0  19.465860  20.006960  0.0  10.00  14.0  21.00   
16   Men/Tops/T-shirts   760.0  16.109211  12.252285  0.0  10.00  13.0  18.00   
17   Men/Tops/T-shirts  1084.0  22.675738  16.602886  0.0  12.00  18.0  26.00   
18   Men/Tops/T-shirts   840.0  15.193452  10.164371  3.0   9.00  13.0  17.00   
19   Men/Tops/T-shirts  1288.0  16.182453  13.781346  0.0   8.00  12.0  19.00   
20   Men/Tops/T-shirts  1513.0  20.794448  16.998815  0.0  11.00  16.0  24.00   
21   Men/Tops/T-shirts   839.0  22.353993  18.076933  0.0  10.00  15.0  27.00   
22   Men/Tops/T-shirts   898.0  22.978285  18.061113  4.0  12.00  18.0  28.00   
23   Men/Tops/T-shirts  1034.0  18.926499  14.965349  3.0  11.00  15.0  21.00   
24   Men/Tops/T-shirts   744.0  17.400538  13.114910  0.0  11.00  14.0  19.00   
25   Men/Tops/T-shirts   641.0  17.034321  13.055605  3.0  10.00  14.0  19.00   
26   Men/Tops/T-shirts   539.0  19.831169  17.133178  0.0  10.00  14.0  23.00   
27   Men/Tops/T-shirts   571.0  18.697023  18.773469  0.0   9.00  12.0  21.00   
28   Men/Tops/T-shirts   501.0  23.784431  22.356060  3.0  12.00  16.0  29.00   
29   Men/Tops/T-shirts   479.0  16.519833  13.724391  0.0  10.00  14.0  18.00   
..                 ...     ...        ...        ...  ...    ...   ...    ...   
71   Men/Tops/T-shirts   165.0  37.496970  32.926308  5.0  15.00  25.0  49.00   
72   Men/Tops/T-shirts   210.0  18.571429  12.878049  3.0  11.00  14.0  20.75   
73   Men/Tops/T-shirts   233.0  17.096567  10.879449  5.0  10.00  15.0  20.00   
74   Men/Tops/T-shirts   472.0  21.461864  17.511374  3.0  12.00  15.0  26.00   
75   Men/Tops/T-shirts   278.0  16.201439  15.987215  5.0  10.00  13.0  18.00   
76   Men/Tops/T-shirts   291.0  16.130584   9.872120  0.0  10.00  14.0  19.00   
77   Men/Tops/T-shirts   255.0  14.964706   9.308510  3.0   9.00  12.0  17.00   
78   Men/Tops/T-shirts   279.0  13.777778   7.841556  3.0   9.00  11.0  16.00   
79   Men/Tops/T-shirts   609.0  20.047619  16.001008  3.0  10.00  14.0  23.00   
80   Men/Tops/T-shirts  1014.0  25.862919  24.666621  0.0  12.00  16.0  31.00   
81   Men/Tops/T-shirts   120.0  18.958333  19.668426  6.0  10.00  14.0  20.00   
82   Men/Tops/T-shirts    37.0  20.918919  16.238463  7.0  12.00  15.0  21.00   
83   Men/Tops/T-shirts   242.0  17.838843  14.768015  3.0   9.00  13.0  22.00   
84   Men/Tops/T-shirts   142.0  21.140845  17.727085  3.0  10.00  15.0  24.75   
85   Men/Tops/T-shirts   166.0  22.981928  22.813200  5.0  13.00  17.0  25.75   
86   Men/Tops/T-shirts   118.0  34.288136  23.323112  6.0  16.00  32.0  45.00   
87   Men/Tops/T-shirts   182.0  17.840659  11.317219  4.0  11.00  15.0  21.00   
88   Men/Tops/T-shirts    11.0  22.81818

In [87]:
pd.set_option('display.max_colwidth', -1)
train_df.loc[(train_df['category_name'] == 'Men/Tops/T-shirts') & (train_df['item_description'].str.contains('lauren'))]

train_id                                     name  item_condition_id  \
43519    43519     Vintage goldberg wcw 90z t shirt         3                   
176406   176406    Ralph lauren!                            3                   
186074   186074    NIKE ORANGE SHORT SLEEVE SHIRT SIZE M    3                   
223085   223085    white ralph lauren polo t shirt          2                   
247257   247257    Stussy baseball jersey                   3                   
266625   266625    Super rare vintage tupac tshirt rap      1                   
273624   273624    Vintage Ralph Lauren Polo Jeans T Shirt  2                   
315541   315541    vintage polo winter sport long sleeve    3                   
386624   386624    Ralph Lauren Embroidered Logo Shirt Med  3                   
442010   442010    Polo ralph lauren shirt                  1                   
488040   488040    Polo ralph lauren bundle (Gray only)     3                   
492657   492657    Polo ralph lauren bundle                 3                   
522454   522454    Polo ralph lauren bundle                 3                   
802158   802158    2 vneck polo ralph lauren shirts         3                   
829532   829532    Polo ralph lauren bundle                 3                   
959793   959793    Polo ralph lauren bundle                 3                   
999157   999157    Vintage Nike Made in USA ringer tee      3                   
1106458  1106458   In-n-Out souvenir t-shirt                3                   
1175875  1175875   ASU "Let's Kick Some Axe" T-Shirt        3                   
1247531  1247531   Vintage Ralph Lauren Polo Jeans Co. T    4                   
1386300  1386300   Vintage Tommy Hilfiger Shirt             3                   

             category_name         brand_name  price  shipping  \
43519    Men/Tops/T-shirts  Vintage            16.0   0          
176406   Men/Tops/T-shirts  Polo Ralph Lauren  21.0   0          
186074   Men/Tops/T-shirts  Nike               12.0   0          
223085   Men/Tops/T-shirts  Polo Ralph Lauren  27.0   0          
247257   Men/Tops/T-shirts  Stussy             25.0   1          
266625   Men/Tops/T-shirts  Vintage            15.0   1          
273624   Men/Tops/T-shirts  Polo Ralph Lauren  15.0   1          
315541   Men/Tops/T-shirts  Polo Ralph Lauren  20.0   0          
386624   Men/Tops/T-shirts  Ralph Lauren       16.0   1          
442010   Men/Tops/T-shirts  Polo Ralph Lauren  18.0   0          
488040   Men/Tops/T-shirts  Polo Ralph Lauren  16.0   0          
492657   Men/Tops/T-shirts  Polo Ralph Lauren  19.0   0          
522454   Men/Tops/T-shirts  Polo Ralph Lauren  19.0   0          
802158   Men/Tops/T-shirts  Polo Ralph Lauren  16.0   0          
829532   Men/Tops/T-shirts  Polo Ralph Lauren  19.0   0          
959793   Men/Tops/T-shirts  Polo Ralph Lauren  30.0   0          
999157   Men/Tops/T-shirts  Nike               14.0   0          
1106458  Men/Tops/T-shirts  NaN                16.0   0          
1175875  Men/Tops/T-shirts  Gildan             9.0    0          
1247531  Men/Tops/T-shirts  Polo Jeans Co.     12.0   1          
1386300  Men/Tops/T-shirts  Tommy Hilfiger     36.0   0          

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item_description  
43519    Size xl. Fits tts. Tags: wcw wwf polo sport ralph lauren hat bear tommy hilfiger big logo champion basketball jersey                                                                                                     